### ISSUE TITLE
Travelnet "squatting" issue

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#241]
```
The propagation of TravelNet boxes is out of control. 
Maybe we can limit the number of endpoints to a network (6) and the number of networks (3). 
Maybe increment number of networks with XP milestones (Copper, Gold, Diamond, etc)
```

**Comment by OgelGames** [comment]
I agree that TravelNets are being overused currently, but instead of restricting the networks, id say to put some kind of dampener on the boxes themselves.
I personally think TravelNet boxes are way to easy to craft for how powerful they are, and the recipe could be made more like technic machines, i.e. multiple levels of crafting, using expensive materials.
Another option would be to remove the crafting recipe completely, and put them in the compatibility shop at spawn for a high price, maybe around 1-2k mg.

**Comment by thomasrudin** [comment]
I don't know if i do anything yet, the text above was from an ingame mail/complaint.
Didn't hear back from him after i asked back...

**Comment by OgelGames** [comment]
I thought that was the case, just wanted to share my thoughts, being a heavy user of travelnets myself. I'm totally fine if nothing is changed ;)

**Comment by thomasrudin** [comment]
No feedback, guessing it is solved somehow or not important anymore, closing..
