### ISSUE TITLE
Depositors trick Players searching on the live map

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#247]
Posting on behalf of locko, copied without alterations from /mail:

I searched for a possibility to buy cheap coal. The best deal on the live map was buying 5 coal for 1 mg at Rabbit1's store.
The search gives: (Rabbit1	Ground	5380/118/11118	Shop, trading 5xdefault:coal_lump for 1xcurrency:minegeld Stock: 0), but being there it turned out it buys 1 coal for 5 mg.
The same goes for the silver ingot there: (Rabbit1	Ground	5380/118/11118	Shop, trading 5xdefault:coal_lump for 1xcurrency:minegeld Stock: 0), but the vendor is set vice-vers-ca.

But: When i set a fancy vendor to a depositor, it just changed the displayed thing and did not switch the actual trading goods (thanks to Amsi for testing).

**Comment by thomasrudin** [comment]
Do you think it will get better if the search result is displayed properly? (icons and such)

**Comment by int-ua** [comment]
Looks like the problem is that results are shown in incorrect order in case of when vendor is set as depositor (whatever that means, didn't notice such option previously :) )

**Comment by lockonrzwei** [comment]
I made an account now:
Vendors set to depositors keep their originial Offer, they just change the displayed icon in the box. This is good, since if you want to buy things, the wanted good is displayed instead the Minegeld notes.
But some depositors are misleading on the live map: They pretend selling 5 coal for 1 mg on the live map, but in reality they buy instead it is buying 1 coal for 5 mg. So the traded goods are changed on the list on the map.

**Comment by thomasrudin** [comment]
Looks like the vendors in that area have the same glitch, i could not reproduce this isse :confused: 
I put some icons on the search result to clarify it (shopping cart = output item / money bill = input item)

If this happens again, feel free to reopen and post a link to the vendor/depositor
