### ISSUE TITLE
Support/Maintenance

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#260]
<img src="https://acimg.auctivacommerce.com/imgdata/0/2/0/4/2/7/webimg/4057844.jpg"/>

Due to the popularity of the server i find myself with less and less time on my hands.
But i think thats a good sign: pandorabox gets more popular!

With that i want to apologize:
**i can't do everything on the issue list.** :confused: (solely anyways)

So, if you have a bug, feel free to open a new issue but don't expect it to be resolved anytime soon.
If (by any chance) you have the technical skills to fix an issue, don't hesitate to open a PR or ask for write permissions on the repo, i don't have problems with giving access to people...

(Thanks to everybody that submitted patches/PR's by the way :smile:)

I don't plan to retire or anything, don't worry. I always invested a few hours a week for development and playing, but that time will not be enough to fix _all_ issues it seems...
Also: i don't wan't to be dictated by only fixing things:

<img src="http://blogs.elon.edu/gst336/files/2014/06/imgres.jpg"/>

Currently on my have-fun list is:
* Implementing some kind of 3D view on the mapserver
* Scaling the minetest-engine (less lag, more players)
* Building awesome stuff ingame

(this is just a head-up/fyi issue, i hope it gets understood as such...)

**Comment by Su20ma** [comment]
I suggest we restructure the moding infrastructure **sanely**.

**The server has 22 forked mods**, and we have [mods](https://github.com/pandorabox-io/mobs_xenomorph) that override [forked mods](https://github.com/pandorabox-io/mobs_scifi) behaviour(half of the stuff in the custom pandorabox repo shouldn't be stand-alone lua files).
**The server also has 37 mod repos** and some of the mods are just useless since other mods provide better alternatives IMO

[Not implementing features is hard](http://weblogs.mozillazine.org/roc/archives/2010/06/not_implementin.html).
JWZ’s Law of Software Envelopment: “Every program attempts to expand until it can read mail. Those programs which cannot so expand are replaced by ones which can.”

**Comment by coil0** [comment]
I would like to create a repository (perhaps called "pandorabox-mods" or simply "mods") holding references to all installed mods as git submodules. That would be more useful than [mods.md](https://github.com/pandorabox-io/pandorabox.io/blob/master/doc/mods.md) since it would always be up-to-date and reference the exact commits. As far as I can tell, the version of fancy_vend on the server is not using the upstream repo or the master or pandorabox branches of the forked repo because all three branches have some changes (the customer view) that don’t seem to be on the server. If there are mods with no git repo (the URL for the atm mod was dead when I looked for it), they could be added on the pandorabox-io org.

It’d be possible to reproduce the same version of mods running on the server with `git clone --recurse-submodules`, to identify the change that causes a performance issue by testing the set of mods running at a previous point in time, and to test changes before making them live, with less chance of using the wrong version of the mod or forgetting to update something. I’d like to use that.

**Comment by thomasrudin** [comment]
@Su20ma Yes, there is a mess right now :)
I reduced the stray repos from 64 to 44 but i have still some cleanup to do: #276

@coil0 you should have an invitation

**Comment by thomasrudin** [comment]
closing this: performance is good now (not perfect though), all mods and the engine-modifications are open-source and can be extended if there is an enhancement.

Next issue will be free disk-space, but https://github.com/thomasrudin-mt/mtpurge should take care of that when it is ready...
