### ISSUE TITLE
Excessive technic machines

### ISSUE THREAD

**Issue by MilesBDyson** [pandorabox-io/pandorabox.io#308]
as of recently we all have noticed a major increase of lag, a few weeks ago i have seen conversations in the local chat of a few players building massive amounts of technic machines, centrifuges furnaces and other machine in excess of 400 to 500 machines, i am no expert but i would have to guess that this can not be good for server performance, its almost like a player wants to make something fast so there idea is to make more machines which in fact slows the server and ultimately slowing the production of there machines, so they decide to make more machines. 

as this vishis circle continues it only kills the server, I have seen this in the past when running my own server a few years back.. this is the limitations of Minetest and nothing can really be done about it, as the map database grows in size the server simply slows down, the bottleneck seams to be between the game and the database, now add the technic mod with massive amounts of machines on top of all that and you get serious lagg..

a few ideas on how to combat this would be to limit the total amount of machines a player can place/own (no idea how to do that).. use the xp mod to limit the use of the tecnic mod
such as the first level can only make lv stuff next level can make mv stuff and so on.. 

any way i think until this issue with the excessive use of the technic machines is resolved the server will only continue to become more and more laggy until you reach the point to where only a few players can actually log in ultimately killing the server....

**Comment by thomasrudin** [comment]
> as of recently we all have noticed a major increase of lag, a few weeks ago i have seen conversations in the local chat of a few players building massive amounts of technic machines, centrifuges furnaces and other machine in excess of 400 to 500 machines, i am no expert but i would have to guess that this can not be good for server performance, its almost like a player wants to make something fast so there idea is to make more machines which in fact slows the server and ultimately slowing the production of there machines, so they decide to make more machines.
> 
> as this vishis circle continues it only kills the server, I have seen this in the past when running my own server a few years back.. this is the limitations of Minetest and nothing can really be done about it, as the map database grows in size the server simply slows down, the bottleneck seams to be between the game and the database, now add the technic mod with massive amounts of machines on top of all that and you get serious lagg..
> 
> a few ideas on how to combat this would be to limit the total amount of machines a player can place/own (no idea how to do that).. use the xp mod to limit the use of the tecnic mod
> such as the first level can only make lv stuff next level can make mv stuff and so on..
> 
> any way i think until this issue with the excessive use of the technic machines is resolved the server will only continue to become more and more laggy until you reach the point to where only a few players can actually log in ultimately killing the server....

I can say for sure that the source of the lag is **not** the technic machines (not directly anyway...)

This is an average graph from the stats page with the ABM-timings (in usage per second):
<img src="https://i.imgur.com/ZJyZsYK.png"/>

The average here is about 20 milliseconds, but goes up to 100 ms (per second) so the usage would be about 10% of the server cycle, max.

There is another issue i'm observing for the last few weeks:
<img src="https://i.imgur.com/ABYpbKq.png"/>

This is the graph for the received blocks (`ack` from client). The sent blocks look similar.
The reason im citing those stats is, that i'm guessing the current lag is not actually (server) lag:
I've made some modifications about a month ago for the network code (see #230 -> receive exhaustion).
The server seems to hum along just fine, it is just that the interaction-commands don't get through from time to time. I'm guessing because of the increased block-sends.

The source of the block-send activity would be more changes in far away blocks (mesecons, node-breakers, etc).

I'm currently trying to adjust the server-settings to only send the near blocks with priority and send the far away blocks if the queue is empty (#309).

If you have some advice settings-wise, please go ahead :)

On the database/postgres-front:
I rewrote the laggy part of the database-connection (also in #230, async db) so it does the `insert` part in a separate thread, this helped lag a lot actually (https://github.com/minetest/minetest/pull/8686)

**Comment by MilesBDyson** [comment]
my server was about 4 years ago before all the stats stuff was available so i am speaking from speculation (server logs and htop) but i do know that when players started creating massive collections of machines and tubes with mesecons and other heavy mods, the server began to suffer from lag much like with yours... eventually the server that normally had any where from 40 to 45 players during peek time dwindled down to 6 or 7 

for this server i do wonder is it a rented or dedicated server in a farm some where or is it running on an ip in some ones basement.... as i do know that some ISP will limit bandwidth after x gig is reached per month.. just a thought 

also you may want to look at the strict protocol checking = true ... that might help if you cut out all the older clients and make them upgrade .. another thought ..

if you say that's not the case then i am wrong and i am sorry .. as for the database part i am glad to hear the more improvements have been made to the engine..

**Comment by MilesBDyson** [comment]
well as it seams so much has changed in minetest since i last messed with it .. i hesitate to mention this for i am not sure if its suppose to do this or not but i did notice that on my local dev server .. compiled two days ago with resent mods updated today, the machine i built so i could wright the code for the luacontroller (mentioned earler in game email) keeps running regardless if im logged in or not .. the user account is the admin account listed in the minetest.conf file .. as i was working with the map i noticed that the luacontroller was still taking things out of the chest as i was clear across the map .. so i decided to test it a bit, logged out of the server (server is on another machine) i watched the terminal output on the mintest server ... it still kept running.. as i was not even logged in, the luacontroller was still running and taking things out of the chests.. 

so if this is the case would that not mean that every luacontroller on the map would keep running regardless if the user is logged in or not ?? 

seams a bit strange to me but then again as i said earlier so much has changed..  thought it was at least worth a mention.....

**Comment by thomasrudin** [comment]
> so if this is the case would that not mean that every luacontroller on the map would keep running regardless if the user is logged in or not ??

That was fixed in a setting introduced by a PR of mine: https://github.com/minetest-mods/mesecons/pull/449
The original code was made by @Joe7575

The setting is `luacontroller_lightweight_interrupts` to enable the controllers only in loaded areas...
