### ISSUE TITLE
Flying snow slabs

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#313]
Create abm with moderate chance to "touch" flying snow slabs (happens mostly after ~~woodcutting~~ chainsawing)

Node: `default:snow` or even `group:falling_node`
Touch-function: `minetest.check_single_for_falling(pos)`

**Comment by OgelGames** [comment]
Main cause of this is actually chainsaws, not woodcutting, which seems to be because they cut the tree differently.

The woodcutting mod does it with minetest.node_dig (https://github.com/thomasrudin-mt/woodcutting/blob/5eea8430e4cd28a95aa06849f03c968feda33e33/init.lua#L244), but the chainsaw uses minetest.remove_node (https://github.com/pandorabox-io/technic/blob/264bfef6027c0da510aafbef6a7898b467e678c3/technic/tools/chainsaw.lua#L326), which seems to not update the nodes around it.

Possible fix would be to check for falling nodes after removing the node.

**Comment by thomasrudin** [comment]
> Possible fix would be to check for falling nodes after removing the node.

I think we need both:
* a proper chainsaw execution
* and a way to deal with all the _existing_ flying snow slabs...

I'll implement a slow ABM in the `pandorabox_custom` repo to deal with the existing nodes. They should be cleaned up over time eventually...
