### ISSUE TITLE
forcefield emitter break reactor

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#346]
This bug allow for new genration griefing :smiley:

Spreading forcefield throught the water in reactor, cause that nuclear core break to corium.

**Comment by thomasrudin** [comment]
This was partially mitigated by a protection check of the forcefield emitters here:
https://github.com/minetest-mods/technic/pull/468
No one else, except you can change your forcefield-settings.

But yes: if you wanted, you could bring a running nuclear reactor to a meltdown with a forcefield. But you could also dig some nodes from the reactor, nothing stops you from doing that... :rofl: 

I don't think that can (or should be) made idiot-proof...
Otherwise we *should* prevent lots of other stuff too, for example jumping off a cliff is deadly too, should that be prevented too? :P

**Comment by SwissalpS** [comment]
as long as nobody else can destroy my reactor, I'm fine with it the way it is.

**Comment by thomasrudin** [comment]
closing this, there are enough protection-possibilities right now...
