### ISSUE TITLE
Some crafted tools don't have a level and node counter when same tools crafter previously do

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#389]
Mentioned by Yad in #main, verified by me on mithril pickaxe. New one I just crafter didn't show node counter even after using it but I have two 6th level mithril pickaxes in storage.

**Comment by OgelGames** [comment]
So I found the issue; silver and mithril tools (from `moreores`) are not overridden with `toolranks` descriptions. Still can't find why it was working before though...

BTW, the description is part of the tool's metadata, that's why your other pick still shows its level 😉 (also I think if you used that old pick, the node count would not go up)

**Comment by OgelGames** [comment]
I've opened two PR's to fix this issue: https://github.com/minetest-mods/moreores/pull/37 and https://github.com/lisacvuk/minetest-toolranks/pull/7

Optionally my forks can be used to fix it on the server in the meantime: https://github.com/OgelGames/moreores and https://github.com/OgelGames/minetest-toolranks

**Comment by thomasrudin** [comment]
Thanks @OgelGames, i switched to your forks and subscribed to the PR's :smile:
