### ISSUE TITLE
constructor -> protector removal

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#396]
Report from `chi`

```
I discovered that protection blocks can be destroyed through protection, using a piston, constructor mark 3 and mese blocks.

It's done by constructing a piston inside the protected area to push a node breaker and line of mese up against the protection block then using a constructor to replace the piston with mese.

I think preventing constructors from modifying protected nodes might have to be done eventually. If that can't be done can maybe stop them placing node breakers, deployers, movestones and pistons?

Unlisted demonstration video, the first part is setting up a protection block I can't modify any-more to demonstrate that it actually works: https://youtu.be/qSfVFn1sSHM

A temporary measure I can think of is to use areas with 21 nodes worth of space surrounding them to protect structures from this. I don't think pistons can push more than 16 nodes.
```

Possible mitigation:
* https://github.com/pandorabox-io/pandorabox_custom/blob/master/mvps_stopper.lua#L3

**EDIT**: i thought i could hide that issue somehow from the public... turns out i can't... :P

**Comment by OgelGames** [comment]
Yet another part of the `technic` to fix :smile: 

Also not the first time these were able to be exploited: https://github.com/minetest-mods/technic/issues/503

Fixing the code of the constructors so they check the protection is the best way to fix this, like chi said.

**Comment by coil0** [comment]
The node breaker digs on behalf of the player who owns it, so you can’t dig other players’ protection blocks. This works only because the protector block and the node breaker were both owned by the empty string (since they were both placed by the constructor, so they had no metadata and the owner was just "").

**Comment by OgelGames** [comment]
Yes, which is because the callbacks used to set that data are not called by the constructor.

**Comment by thomasrudin** [comment]
> both owned by the empty string

Oh, right, this is invalid then... :+1:

**Comment by OgelGames** [comment]
> this is invalid then...

Yes, I just tested it on a local test server (using two players), and it's not possible to remove the protector block because the node breaker won't dig it.

However, a protection check still needs to be added to the constructor, as it is still possible to place and remove blocks in a protected area using the constructor.
