### ISSUE TITLE
Technic protected chest update

### ISSUE THREAD

**Issue by BobFred7** [pandorabox-io/pandorabox.io#486]
minetest-mods/technic#542

I saw a PR on the main technic repo that seems to be adding protected (shared) versions of all the technic chest types. On pandorabox.io there is already a mithril protected chest, and there are no protected chests existing in the official version of technic. It's possible this PR will sit around for weeks (like mine have) and not get merged, but if it does get merged, this could produce some conflict that must be resolved.

**Comment by S-S-X** [comment]
Protection seems to be similar what it currently is on pandorabox.

There will be merge conflict for sure but it seems that it is not really big issue because item id is same, protection is similar, upstream chests can probably simply override current modifications done for https://github.com/mt-mods/technic @ https://github.com/mt-mods/technic/commit/5bddd0c7fae8543585255d9aa55c634972160a2d

If wanted we could also merge those chests before pr gets accepted.

One thing I noticed (or maybe didn't notice) was that there is not visual indicator for protected chests, mt-mods fork does it like this:
https://github.com/mt-mods/technic/blob/1a9d4ccc7d554c813e34856ac6c70a7bafb085cd/technic_chests/register.lua#L262-L265

```
	if data.protected and has_protector_mod then
		-- use overlay from protector mod
		table.insert(front, "protector_logo.png")
	end
```

So if similar visual indicators wont end up into upstream repo then it will also need some local modifications for merge to keep visual indicator for protected chests.

**Comment by Sires0** [comment]
Hello. About the overlay, I planned to put it but I was waiting for some answer in the PR since that code could be useful for other protection mods as well.

**Comment by BuckarooBanzay** [comment]
> Edit: Just realized this is not technic repo xD

Nope :smile: but your PR looks good, good luck getting that through... :+1:

**Comment by BuckarooBanzay** [comment]
closing this, the `pull` bot creates a PR or commits automatically from the upstream repo (or even reports conflicts)
