### ISSUE TITLE
Beehive injector support

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#490]
A few players have mentioned this before, that `pipeworks` injectors should be able to pull honey out of beehives.

Not sure if it's better to make the `pipeworks` injector support the beehive inventory, or add pipeworks support to the beehive, but the latter would be possible to do just by overriding the beehive in `pandorabox_custom`.

https://notabug.org/TenPlus1/mobs_animal/src/master/bee.lua#L73

https://gitlab.com/VanessaE/pipeworks/-/blob/master/filter-injector.lua#L71

**Comment by BuckarooBanzay** [comment]
Sounds good.. overriding the node definition will be the most compatible implementation with regards to future changes...

**Comment by S-S-X** [comment]
Another method for automated honey collection could be grabbing whole beehive and throwing it into centrifuge. That method would require wear property for beehives.

I would like this more than simple injector as it resembles real world methods a bit better where you actually do use centrifuges to extract honey from honeycombs.

ABM to replenish beehive wear value and centrifuge to extract honey from beehive.

This would make centrifuges a bit more useful which would also be nice thing.

**Comment by OgelGames** [comment]
> I would like this more than simple injector as it resembles real world methods a bit better where you actually do use centrifuges to extract honey from honeycombs.

Something like this? https://notabug.org/TenPlus1/bees

While I like the realism, I don't think it's necessary or worth the time to make it all compatible...

**Comment by S-S-X** [comment]
> Something like this? https://notabug.org/TenPlus1/bees
That would be awesome and also seems like it tells a lot about beekeeping but also seems like a bit complicated update.

But at first I was thinking more like easy approach by adding local customization that would add centrifuge recipe for beehive and allow getting honey with technic centrifuges.

**Comment by S-S-X** [comment]
![screenshot_20200419_190803](https://user-images.githubusercontent.com/50966843/79693114-84412a80-8271-11ea-9a1e-63ce868c8105.png)
![screenshot_20200419_191140](https://user-images.githubusercontent.com/50966843/79693144-a9359d80-8271-11ea-82ce-71fffadb24b4.png)

code: https://github.com/S-S-X/centrifuge-bees/blob/master/init.lua

**Comment by OgelGames** [comment]
> Tried with approach that allows stacking beehives so there's no metadata for items.

That looks great :+1: Probably close to the best solution for compatibility.

**Comment by BuckarooBanzay** [comment]
> Tried with approach that allows stacking beehives so there's no metadata for items.

Nice idea, looks good :+1:

**Comment by S-S-X** [comment]
Made small update to code which makes centrifuging a bit more efficient when there's more honey in beehive so 1/12 takes significantly more time than 12/12 per honey produced.

`time = ( i + 2 ) * 3 - i`

| Honey | Total time | Time/item |
| -------- | ----------- | ------------ |
| 1/12 |8|8.0|
| 2/12| 10|5.0|
| 3/12| 12|4.0|
| 4/12| 14|3.5|
| 5/12| 16|3.2|
| 6/12| 18|3.0|
| 7/12| 20|2.857142857142857|
| 8/12| 22|2.75|
| 9/12| 24|2.6666666666666665|
| 10/12| 26|2.6|
| 11/12| 28|2.5454545454545454|
| 12/12| 30|2.5|

So it is a lot better to grab full beehives instead of partially filled ones.

I feel like there's no opposition so far so maybe we can soon put up pr to pandorabox-mods repo.

**One thing that must be fixed:** digging beehives most probably wont respect protections properly because it overrides `on_dig` which I think is supposed to handle everything about digging, including calling global handlers and / or protection checks.

I think on_place is probably safe as it calls minetest.item_place which should already handle events under the hood.

**Comment by S-S-X** [comment]
Should maybe also mention that this line is **Minetest 5.2 only**: https://github.com/S-S-X/centrifuge-bees/blob/a10dae47bdddcf01a5b28a3ba4fbb7c0091eb206/init.lua#L30
Wont work with earlier versions.

**Comment by OgelGames** [comment]
> **One thing that must be fixed:** digging beehives most probably wont respect protections properly because it overrides `on_dig` which I think is supposed to handle everything about digging, including calling global handlers and / or protection checks.

Yes, it does, here is the code: https://github.com/minetest/minetest/blob/master/builtin/game/item.lua#L550-L651

I think adding a protection check is all that is necessary though, which is as simple as adding a line like this at the start of the `on_dig` code:

```lua
if minetest.is_protected(pos, digger) then return end
```

**Comment by BuckarooBanzay** [comment]
> Should maybe also mention that this line is **Minetest 5.2 only**: https://github.com/S-S-X/centrifuge-bees/blob/a10dae47bdddcf01a5b28a3ba4fbb7c0091eb206/init.lua#L30
> Wont work with earlier versions.

Uff, are you sure? I _think_ i've used `minetest.item_place` even before 0.5 ... :astonished:

**Comment by OgelGames** [comment]
@BuckarooBanzay see here: https://github.com/minetest/minetest/commit/80af58c8c5a68fc7ff66a730204ffa933e89a305

**Comment by OgelGames** [comment]
Everything is working, I think this can be closed now :wink:
