### ISSUE TITLE
Lag reduction discussion (lava flans, digtron, etc)

### ISSUE THREAD

**Issue by BobFred7** [pandorabox-io/pandorabox.io#504]
Players frequently go afk for significant amounts of time to run lava flan traps. Extra players afk is not such a good thing, and I think it would be beneficial in other ways if lava flan spawning were to be modified, my idea here is to make spawning much more frequent but only occur if the nearby player is moving/active. Comments?

**Comment by OgelGames** [comment]
> Players frequently go afk for significant amounts of time to run lava flan traps. Extra players afk is not such a good thing

True, but a lot of players also afk at quarries and other technic machines, which is worse for the server.

> my idea here is to make spawning much more frequent but only occur if the nearby player is moving/active.

As far as I know, this is not possible with the way mob spawning works...

**Comment by BuckarooBanzay** [comment]
> > Players frequently go afk for significant amounts of time to run lava flan traps. Extra players afk is not such a good thing
> 
> True, but a lot of players also afk at quarries and other technic machines, which is worse for the server.

The current bottle-neck is maploading and digtron-usage (see digtron-stats when the min-lag is elevated), afk'ing near machines or lava-flan farms is not an issue in my opinion.

> 
> > my idea here is to make spawning much more frequent but only occur if the nearby player is moving/active.
> 
> As far as I know, this is not possible with the way mob spawning works...

Could be done somehow but requires a lot of work (poll the afk-mod or roll-your-own and intercepting the spawning abms)

**Comment by OgelGames** [comment]
> The current bottle-neck is maploading and digtron-usage (see digtron-stats when the min-lag is elevated)

So in a way afk players are actually better than players running around :smile:

**Comment by S-S-X** [comment]
There could be cheap way to check for mapblocks activated by afk players and to have afk property for players. As already said this flan farm probably is not thing to use it for but it could be used for more expensive operations like mesecons, technic and pipeworks (mostly to stop self contained injector and vacuum tubes).

How many problems this would solve? Is is worth it?

Motivation seems to be an attempt to reduce afk players to reduce lag. Maybe there could also be lag free days: mesecons, pipeworks, quarries and digtrons disabled 1-2 days / week. Maybe power networks capped to 10-20kEU.

Not sure if this is what most players want, other suggestions?

**Comment by BuckarooBanzay** [comment]
> Motivation seems to be an attempt to reduce afk players to reduce lag. Maybe there could also be lag free days: mesecons, pipeworks, quarries and digtrons disabled 1-2 days / week. Maybe power networks capped to 10-20kEU.

"no-mesecons sundays" :smile: 

but seriously: this does sound interesting but i fear that not everybody will enjoy this... :confounded:

**Comment by BobFred7** [comment]
> > Motivation seems to be an attempt to reduce afk players to reduce lag. Maybe there could also be lag free days: mesecons, pipeworks, quarries and digtrons disabled 1-2 days / week. Maybe power networks capped to 10-20kEU.
> 
> "no-mesecons sundays" 
> 
> but seriously: this does sound interesting but i fear that not everybody will enjoy this...

reduce priority/intensity on running mesecons/pipeworks/technic/digtrons when no players nearby are being active?

**Comment by BobFred7** [comment]
> The current bottle-neck is maploading and digtron-usage (see digtron-stats when the min-lag is elevated), afk'ing near machines or lava-flan farms is not an issue in my opinion.

Or decrease maximum movable digtron size

**Comment by S-S-X** [comment]
> > The current bottle-neck is maploading and digtron-usage (see digtron-stats when the min-lag is elevated), afk'ing near machines or lava-flan farms is not an issue in my opinion.
> 
> Or decrease maximum movable digtron size

I've been using large trons lately because I am removing mars.

Decreasing movable digtron size wont help much because players do know that they can always run multiple trons.
Also decresing maximum size again limits a lot how digtrons can be used. Again I'd like to propose different approach for limiting trons and maybe even increasing maximum digtron sizes.

### Increasing digtron sizes to reduce lag???
Well increasing maximum size is not core of my proposal, instead calculate minimum delay for digtron and maybe even add simple tracking for running digtrons per player account.

Make 1 digtron component consume say 100 milliseconds of player specific digtron quota, digtron with 75 components would then have minimum delay of 7.5 seconds.
10 component tron can still run 1 second intervals.

To extend this add tables for started digtrons / player and start adding extra 200ms delay / component after exceeding total running trons 75 component soft limits.

### Example situation based on above fairly simple and straightforward quota values:
Then if player has started one 75 component tron which is running at 7.5 second delay and starts another 75 component tron then that newly started tron will have minimum delay of 22.5 seconds.

Another example if larger trons would be allowed would be say 125 component tron started and only tron started by said player, that tron would have minimum 22,5 seconds delay.

Third example player starts 30 component tunnel builder, it would have minimum 3 seconds delay.

**Comment by BuckarooBanzay** [comment]
@S-S-X variable time delay does sound optimal even for big trons, but that needs some major refactoring of the digtron code...

With that said: i'm tempted to fork the main `digtron` repository but i think i wait a bit more to see if FaceDear tends to it again

>  I'll remove just small part of mars, max 50 million nodes.

:astonished: 
<img src="https://ksr-ugc.imgix.net/assets/027/105/110/da3d94723f66cdca25124d17d20d49a8_original.jpg?ixlib=rb-2.1.0&crop=faces&w=1024&h=576&fit=crop&v=1572990790&auto=format&frame=1&q=92&s=098152035d0f5929424fdf0ef4ef0206"></img>

by the way: i think this is getting off-topic :stuck_out_tongue:

**Comment by BobFred7** [comment]
> by the way: i think this is getting off-topic

We'll keep discussing this, I'll change the title

**Comment by BuckarooBanzay** [comment]
closing this, reopen/recreate if still relevant.

Recent changes:
* `advtrains` mod only runs trains near players now (significant baseline cpu-reduction)
* technic quarry was rewritten by @OgelGames and is much cleaner and faster now
* `digtron` mod has various protection caching enhancements now (in the `digtron_custom` mod)
