### ISSUE TITLE
wiki login is broken

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#561]
[a3f465833b3fe24d88b082b6] /index.php?title=Special:UserLogin&returnto=Main+Page Error from line 444 of /var/www/html/extensions/ConfirmEdit/SimpleCaptcha/SimpleCaptcha.php: Call to undefined function wfGlobalCacheKey()

Backtrace:

#0 /var/www/html/extensions/ConfirmEdit/SimpleCaptcha/SimpleCaptcha.php(331): SimpleCaptcha->badLoginKey()
#1 /var/www/html/extensions/ConfirmEdit/includes/auth/CaptchaPreAuthenticationProvider.php(43): SimpleCaptcha->isBadLoginTriggered()
#2 /var/www/html/includes/auth/AuthManager.php(2127): CaptchaPreAuthenticationProvider->getAuthenticationRequests(string, array)
#3 /var/www/html/includes/auth/AuthManager.php(2105): MediaWiki\Auth\AuthManager->getAuthenticationRequestsInternal(string, array, array, User)
#4 /var/www/html/includes/specialpage/AuthManagerSpecialPage.php(275): MediaWiki\Auth\AuthManager->getAuthenticationRequests(string, User)
#5 /var/www/html/includes/specialpage/LoginSignupSpecialPage.php(143): AuthManagerSpecialPage->loadAuth(NULL)
#6 /var/www/html/includes/specialpage/LoginSignupSpecialPage.php(235): LoginSignupSpecialPage->load(NULL)
#7 /var/www/html/includes/specialpage/SpecialPage.php(600): LoginSignupSpecialPage->execute(NULL)
#8 /var/www/html/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run(NULL)
#9 /var/www/html/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath(Title, RequestContext)
#10 /var/www/html/includes/MediaWiki.php(940): MediaWiki->performRequest()
#11 /var/www/html/includes/MediaWiki.php(543): MediaWiki->main()
#12 /var/www/html/index.php(53): MediaWiki->run()
#13 /var/www/html/index.php(46): wfIndexMain()
#14 {main}

**Comment by BuckarooBanzay** [comment]
it has been a while since i saw a php stacktrace :smile: 

There were several issues: Since the update to `1.35.0` there have been several broken extensions.
I had to switch `ConfirmEdit`, `WikiEditor` and `MsUpload` to the latest git version.

ConfirmEdit was responsible for the login issues and MsUpload did not work properly with the new wiki version (Upload images bar was missing).
I think i'll make a git submodule repo for the extensions too like with the mods, its better to track changes and i can upload the current state to github for anyone interested in the wiki :yum: 

Looks like the auto-updating does not work that smooth after all :confounded:
