### ISSUE TITLE
Protectors with empty owner name

### ISSUE THREAD

**Issue by 6r1d** [pandorabox-io/pandorabox.io#583]
Hello. Cyriax noticed we can place protectors with no owner using a Constructor Mk1. I helped with removing it, but it's possible.

I wonder what is better: to change constructor or to add `on_place` override for the protectors, so they drop with an empty name.

**Comment by OgelGames** [comment]
It is the constructor that doesn't call the `after_place` callback (and others), but that is one of the special things about it, so I don't think that should be changed.

I think the best way to fix it would be to change the protector code so that protectors with empty owner get ignored, and don't protect anything.

**Comment by 6r1d** [comment]
Thanks, that was fast. :-)
