### ISSUE TITLE
die twice? get 2 hud overlays fighting each other

### ISSUE THREAD

**Issue by wsor4035** [pandorabox-io/pandorabox.io#588]
what the title says
![image](https://user-images.githubusercontent.com/24964441/101588140-b267ac00-39b3-11eb-88d9-8c3aa821f290.png)

**Comment by S-S-X** [comment]
Maybe just clear previous markers if there's already one nearby within some radius?

**Comment by BuckarooBanzay** [comment]
Related: https://github.com/pandorabox-io/pandorabox_custom/issues/28

@PeterNerlich does your `death_markers` mod account for this too, might be a reason more to switch to yours...

**Comment by PeterNerlich** [comment]
Not sure, depending on how this issue occurred. If you died in the same spot twice, they would be distinguished by the color, but they would still be overlaying each other. Though it should remove the marker when you pick up the bones (it checks after a second whether the bones node is still there and removes the marker if not). However, only if the bones are removed *by the owner* by either *punching* the node or *taking all items* (so using the functions registered by the `bones` mod by minetest). I'm considering to address such situations later

**Comment by SwissalpS** [comment]
I actually like having multiple death markers visible, have been able to retrace my steps that way :)

On death a waypoint is added. It is removed after 42 minutes no matter if you die again or the bones have been retrieved.

**Comment by PeterNerlich** [comment]
I mean, it would be easy to just make it a per-player setting you can change with a command, if preferences differ.
I myself think it could be annoying if I die multiple times at the same location and then have to watch this disgrace as a bunch of markers in the same spot for 42 minutes... Obviously over-dramatised, but you get my idea.

Actually, thinking about this I stumbled over the answer for your original question @BuckarooBanzay:
<details>
  <summary>No, they shouldn't occur. (click for the technical explanation)</summary>
  <p>When the HUD is updated for all currently connected players, my Death Markers mod uses a <a rel="nofollow" href="https://gitlab.com/PeterNerlich/death_markers/-/blob/master/init.lua#L130">data structure storing all markers indexed first by player and then by position</a>, meaning that a new marker should overwrite possible old ones at the same position. The associated HUD elements are kept in a <a rel="nofollow" href="https://gitlab.com/PeterNerlich/death_markers/-/blob/master/init.lua#L139">similarly structured table <code>managed_hud_ids</code></a>, which instead of the marker information holds just the id of the HUD element.<br>While updating, every id found still touched by iterating over those data structures is remembered. Finally, any id that has not been touched but is still in <code>managed_hud_ids</code> is cleaned up, thus insuring that no player ever sees two markers for the same position (that stems from the Death Markers mod).</p>
</details>

**Comment by S-S-X** [comment]
> No, they shouldn't occur. (click for the technical explanation)

Practically they probably do still occur and what explained does not really affect actual problem as when looking to waypoints from distance (spawn location) it does not really matter if waypoints are some (depending on distance) nodes apart from each other, would still block each other.

**Comment by PeterNerlich** [comment]
As I understood the original issue, it was about waypoints for the same position, such that there is Z-fighting (rapid flipping to be drawn in front or in the back of the respective other), which should not occur (if minetest works as I think it should, I have not verified that or fiddled with this in the last weeks) if they are a good amount of nodes apart from each other. Of course, from a number of perspectives the representations of those different points in 3d space will still occupy the same space on your 2d screen. If that is what the original issue was actually about, I would recommend a *won't fix*.

**Comment by S-S-X** [comment]
> As I understood the original issue, it was about waypoints for the same position, such that there is Z-fighting

If you take a look at screenshot you can see that z fighting is not the case here, it is 2 death location in close proximity but not exactly same location. y coordinates differ a bit.

True that fixing this properly to make ux better it would need bit more complex system for waypoints, basically you would need to make waypoints visible based on distance between player and waypoints so that if some waypoints would overlap in HUD then only closest of overlapping group would be visible.
But in my opinion not that complex really to warrant simply closing issue because too complicated.

**Comment by BuckarooBanzay** [comment]
> doesn't bones redo 'fix' this?

Oh, it does: https://github.com/OgelGames/bones/blob/master/waypoints.lua#L26 nice :)
