### ISSUE TITLE
various colored items with replacer

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#677]
Reported by @Klaranth and discovered by `TK243`

```
I discovered this error while building my city on Mars and I died. To change the color of things,
I use a tool called "Node Replacement Tool (technique)",
I press the "E" key while holding the tool and left click to change like this,
if I want the object to be green I select the "Field" mode, if I want it to be salmon
I select "crust" and if I want it to return to normal I select "simple", once I select
the mode I change to the inventory number In which is the tool that I want
to change color, for For example, if the tool is in the third space, I select the number "3".
```

<img src="https://i.ibb.co/tQkjXfF/delete.png"/>

Not sure how yet but it looks like `replacer.set_data(stack, ...)` does set the item color with `stack:set_string("color", "")`:
* https://github.com/SwissalpS/replacer/blob/191ef5bf8adb404ea3393da46ac0bfbe56416829/replacer.lua#L604
* https://github.com/SwissalpS/replacer/blob/191ef5bf8adb404ea3393da46ac0bfbe56416829/replacer.lua#L84

Not sure if that can be abused :thinking: (so not a high-prio bug)

**Comment by OgelGames** [comment]
That bug has been known for ages by a few players, lga's museum has a few examples of it too. It does nothing other than tint the inventory image, so it's more of just a fun trick you can use to make unripe bananas :)

**Comment by S-S-X** [comment]
This is related to recent server crash. Basically replacer assumes things that it does not actually check first and those things can be changed easily when using formspec configuration for replacer.

**Comment by Klaranth** [comment]
So is using this bug the reason for more server crashes?

**Comment by S-S-X** [comment]
> So is using this bug the reason for more server crashes?

Not directly but root reason for server crash and doing weird things with some items is same.

**Comment by Klaranth** [comment]
So, should TK stop using it for the time being, or completely, or no problem using it?

**Comment by S-S-X** [comment]
Fix waiting @SwissalpS to review and merge https://github.com/SwissalpS/replacer/pull/30

> So, should TK stop using it for the time being, or completely, or no problem using it?

I cannot answer that, it depends on how well player understands why it works and how it works.

**Comment by SwissalpS** [comment]
thanks, will be testing SX's PR and merging soon. Was a lot of fun while it lasted ;)

**Comment by SwissalpS** [comment]
Have not been able to provoke a crash. If anybody can give steps to somewhat reliably reproduce a crash caused by using this effect, I'd be grateful and put efforts towards fixing it.

I'm not one to plug 'holes' just because they exist without actual 'danger'. Players are having fun with this.
Nobody is getting an unfair advantage from these items and placing them removes the effect.

I can colour items, that's not the steps I need.

Are there machines/recipies that crash the server when coloured items are used?

**Comment by BuckarooBanzay** [comment]
I haven't heard of any color-related crashes with this "bug" :wink: 
This is a low-prio issue but yes: it was kinda nice seeing those odd items pop up here and there

**Comment by S-S-X** [comment]
> I haven't heard of any color-related crashes with this "bug" 😉 This is a low-prio issue but yes: it was kinda nice seeing those odd items pop up here and there

Fix I added only affects that corner case crash (and requires unregistered items to crash). It does not affect coloring or any other weird behavior of replacer.

**Comment by S-S-X** [comment]
Actually I've dropped labels because mentioned fix was not to fix this issue but instead was reply to Klaranth comment:
> So is using this bug the reason for more server crashes?

**Comment by SwissalpS** [comment]
OK, I've patched the part that could crash server.

**Comment by S-S-X** [comment]
For me it is fine if issue stays closed because I don't see problems with it, however it should not be closed because server crash is fixed as that was not original concern but just mentioned here as a side effect of described behavior.

@BuckarooBanzay @OgelGames do you want to keep this open as a reminder to fix root cause? (Basically disallow item coloring + applying other replacer metadata)
My personal opinion is that it does not have to be fixed and only notifying because close reason was not correct for issue description.

**Comment by OgelGames** [comment]
I would actually prefer if it wasn't fixed :D

**Comment by BuckarooBanzay** [comment]
>  My personal opinion is that it does not have to be fixed and only notifying because close reason was not correct for issue description.

Works for me :shrug:
