### ISSUE TITLE
forget loaded mapblocks after 15 minutes - lost of speed if memory free

### ISSUE THREAD

**Issue by Festus1965** [pandorabox-io/pandorabox.io#703]
check your server memory, htop
if there is plenty of NOT used memory (free) after green apps and orange maybe cache

change
https://github.com/pandorabox-io/pandorabox.io/blob/master/minetest.conf#L165

server_unload_unused_data_timeout = 900

to higher value like 3 or even 6 hours (10800 or 21600).
I use 24 hours and so Mapblocks keep longer in FAST memory instead of reloaded if needed. speeds up a lot (at me uses 8 GB RAM mt)
as also a gamer might be out for mining etc. just for 16 minutes and jump /home causes then a reload from HDD

**Comment by BuckarooBanzay** [comment]
Tried that already a while back: downside with this setting is that the server takes _ages_ to shut down (a few minutes due to some write-back ~~crap~~logic).

Besides, there are already several caches for the mapblock data:
* On the physical SSD-layer (or in the virtualization layer of the block-driver)
* The FS-Cache itself on the kernel-layer
* Postgres-cache

## Current stats

This is the status-board for the machine pandorabox runs on (`akheron` is the actual hostname)
https://monitoring.minetest.land/d/rYdddlPWk/node-exporter-full?orgId=1&refresh=1m

This chart shows the memory usage:
https://monitoring.minetest.land/d/rYdddlPWk/node-exporter-full?orgId=1&refresh=1m&viewPanel=24

As you can see: the kernel uses the "unused" memory quite good already

**Comment by Festus1965** [comment]
What ?

the Shutdown even at my server with 32 GB RAM and a setting of 1 day !!!  and about 15-20 GB used data storage
takes about max 30 seconds to shut down.

So a shutdown from about maybe 20 seconds longer is a reason to NOT use this option, that is most closed to the app itself and so most effective ?

And how often are you shut down the server willingly ... We don't talk about crash.
Now the server is running 8 days ...

Another logic that I don't get. 
The advantage of faster have map data against a shutdown maybe once a week ???
