### ISSUE TITLE
Centrifuge recipes don't show on the craftguide, and some other bugs.

### ISSUE THREAD

**Issue by FavoritoHJS** [pandorabox-io/pandorabox.io#757]
You would think the "dirt to clay ball" recipe will appear loud and clear in the crafting guide, but it doesn't.

also some other misc. bugs:
- PickaxeTweaks doesn't work with anything that's not a vanilla pickaxe, this includes Technic, Lava and Obsidian pickaxes, and the Multitools.
- Translucency in items doesn't show when outside of an inventory slot, causing problems with items like charcoal which consist of a large amount of it

**Comment by OgelGames** [comment]
Yeah, that's a known problem with `unified_inventory`, it only supports showing a single output, but the centrifuge has two. I think @S-S-X attempted fixing that at one point.

> * PickaxeTweaks doesn't work with anything that's not a vanilla pickaxe, this includes Technic, Lava and Obsidian pickaxes, and the Multitools.

Obsidian pickaxes should work, support was added in https://github.com/OgelGames/obsidianstuff/commit/470d84910b89627f6535eb914537374df76f576b. As for the others, they will also need support added.

IMO `pick_axe_tweaks` should just automatically add support for any pickaxes that exist.

> * Translucency in items doesn't show when outside of an inventory slot, causing problems with items like charcoal which consist of a large amount of it

That's an engine issue, but it could be fixed by removing the translucency in those textures.

**Comment by FavoritoHJS** [comment]
> Yeah, that's a known problem with unified_inventory, it only supports showing a single output, but the centrifuge has two [...]

A possible workaround is to "borrow" from linuxforks and make unified_inventory see multiple recipes, one for each output. That way at least you'll see how to get an item.

> IMO pick_axe_tweaks should just automatically add support for any pickaxes that exist.

I'm not sure if that's possible, not unless there's a way to programmatically see the "pickaxe-ness" of a tool.

A workaround would be to make a local mod that registers the tools using Pick Axe Tweak's API.

A better solution would be to add that to the original mods.

**Comment by S-S-X** [comment]
I made a test but never pushed it toward real usable feature / PR, I think it was just this here: https://github.com/mt-mods/technic/commit/c9bb7c71f6235d007a3ff7aeffb182c3ab4f0fee
It kinda worked fine but there's still problems with inventory mod support for multiple outputs.
But then also I think that also isn't working for replacements so does it matter?

**Comment by OgelGames** [comment]
> > IMO pick_axe_tweaks should just automatically add support for any pickaxes that exist.
> 
> I'm not sure if that's possible, not unless there's a way to programmatically see the "pickaxe-ness" of a tool.

There is the `pickaxe` group, which can be used to identify the pickaxes, only the multitools are missing that. I might make a PR for that...

**Comment by OgelGames** [comment]
https://github.com/wsor4035/pick_axe_tweaks/pull/1

**Comment by S-S-X** [comment]
Removed "Engine issue" label because engine very much allows having all recipes in guide.
If it is bug is also debatable because recipes have been deliberately disabled, probably because many crafting guide mods did not have good support for multiple output items.
I've heard that some crafting guide mods do have support for multiple outputs, replacements and such.
Not sure what unified inventory exactly supports currently but I think at least there's no complete support unless it has been added very recently.

**Comment by S-S-X** [comment]
Not sure if this is helpful at all but for Technic crafting guide problem there's this issue in original Technic mod, some discussion but not much and probably not really that useful... https://github.com/minetest-mods/technic/issues/585

**Comment by OgelGames** [comment]
Centrifuge recipes added to craft guide in https://github.com/mt-mods/technic/pull/311

As for the transparency issue, not really a bug, and it's something that affects many mods, so I don't think we need an issue open about it.

Closing this.
